apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulumi-kubernetes-operator-cr
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - secrets
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pulumi-kubernetes-operator-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pulumi-kubernetes-operator-cr
subjects:
  - kind: ServiceAccount
    name: pulumi-kubernetes-operator
    namespace: default